// Firebase client SDK — used inside Client Components and the browser.
//
// Fill in once the Firebase project exists:
//   NEXT_PUBLIC_FIREBASE_API_KEY=...
//   NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=...
//   NEXT_PUBLIC_FIREBASE_PROJECT_ID=...
//   NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=...
//
// See Claude Code Prompt 2 (Firebase + auth). Expected exports once
// implemented: `auth` (Firebase Auth instance) and `db` (Firestore instance).
export {};
